### ISSUE TITLE
GPL-529 differentiate between separate RT experiments

### ISSUE THREAD

**Issue by rl15** [sanger/unified_warehouse#115]
**Description**
GPL-529 | As PAM (Rob A) I want to differentiate between separate RT experiments to automatically run secondary analysis to identify true variants (esp with outbreak samples)

**Who the primary contacts are for this work**
James M
Scott T
Rob A
James G

NB James M is going to document the manual process he used to help Rob A in PAM to begin to better understand a solution. 

**Knowledge or Stake holders**
Other people that may have specific knowledge about this work or have a stake in how it is implemented. e.g. John Smith is an expert on x

**Additional context or information**
Any other useful context or information that may be useful.

**Comment by JamesGlover** [comment]
Meeting at 10:30 2020-07-03
Looks like existing MLWH may be sufficient to cover requirements.

**Comment by KatyTaylor** [comment]
Outcome of meeting 10:30 2020-07-03

- Attendees were James M, Rob K, Ian W, Jon K
- Discussed queries James G had provided.
- Main outstanding concern seemed to be, if there is more than one run for the same sample in the MLWH, how to identify the runs from 'RT 1' and 'RT 2' (same sample, put onto different RT plates and library prep performed separately on them).
- Library id is probably sufficient.
- Jon K sent over requirements that Rob A had provided: 
- "“As a data analyst I want to know for each sample the batch date(s) (when the sample was received), the run number(s), the lane(s), the index(ces), and the RT (RT1, RT2) in order to be able to deduplicate appropriately.”
- Seemed like they probably have all the info they need in the MLWH
- They will get back to us if they had any more questions about it
- There was talk of working through an example together where there were more than 2 runs for the same sample.
