### ISSUE TITLE
DPL-004 BUG - Reported some batch ids are not being written in warehouses

### ISSUE THREAD

**Issue by emrojo** [sanger/unified_warehouse#226]
**Describe the bug**
In last period we are receiving RT tickets related with some batches not updated in the warehouse that had to be manually rebroadcasted. 

Batches affected so far:
```
batches affected so far
id, created_at, update_at
81533, 2021-04-21 12:57:59 +0100, 2021-04-28 09:14:46 +0100
81534, 2021-04-21 12:58:41 +0100, 2021-04-28 09:14:24 +0100
81653, 2021-04-23 11:34:18 +0100, 2021-04-28 13:58:31 +0100
81666, 2021-04-24 07:22:15 +0100, 2021-04-26 22:01:26 +0100
81667, 2021-04-24 07:26:25 +0100, 2021-04-27 22:01:38 +0100
81681, 2021-04-26 12:06:09 +0100, 2021-04-28 22:01:40 +0100
81713, 2021-04-27 12:21:40 +0100, 2021-04-28 15:53:01 +0100
```

We also noticed that recently there has been some database disconnections which could be related with this but no confirmation about that for the moment.

**RT Ticket Number**
rt718636, rt718399

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to page '...'
2. Click on button '...'
3. See error

**Expected behaviour**
What was expected to happen.

**Screenshots**

**Desktop (please complete the following information):**
* Windows or Mac?
* Browser Chrome, Firefox, Safari or other?
* Browser version (use 'About' to look up)?

**Additional context**

**Comment by JamesGlover** [comment]
This is almost certainly related to issues we're currently experiencing with dropped connections between OpenStack and the MySQL servers. Currently have open service desk ticket with DH addressing these issues (296719).

Kibana logs:

> ERROR -- : Deadletter: ["Batch",81500]
> Deadletter Exception: MySQL client is not connected 

This error *should* result in a requeue and a pause of the workers, rather than a dead-letter. Indeed, I can see a *very* similar logged exception where we are doing the correct thing:

> WARN -- : Re-queue Exception: Mysql2::Error: MySQL client is not connected: SELECT

The code handling this scenario is undergoing a significant re-work in https://github.com/sanger/warren/issues/2 so should hopefully be resolved, but I'd still like to understand what went wrong.

There are a number of actions needed here, although all are already in progress:
1) Resolve the MySQL sever connection drops (With DH - Service desk ticket 296719)
2) Database should reconnect automatically - Should be addressed in https://github.com/sanger/warren/issues/2

https://github.com/sanger/warren/blob/cb62f1fcedd581bfd0bb449a7081bc84b7c7c28a/lib/warren/framework_adaptor/rails_adaptor.rb#L38-L44

In particular checks a connection out per message. Still need to verify that this re-opens stale connections.

3) Messages should be requeued:

This should have been handled by:
https://github.com/sanger/sequencescape/blob/fa8f3138a16c06287f633467d82fb7048f7346ec/lib/postman/message.rb#L8-L26

However this appears to behave inconsistently. This is adjusted in warren to actually establish that we have database issues by directly checking the connection. 
https://github.com/sanger/warren/blob/cb62f1fcedd581bfd0bb449a7081bc84b7c7c28a/lib/warren/framework_adaptor/rails_adaptor.rb#L8-L30

Still, I'd like to understand why the previous behaviour was inconsistent.

**Comment by JamesGlover** [comment]
Requeued logging:

> Re-queue Exception: Mysql2::Error: MySQL client is not connected: SELECT `submissions`.* FROM `submissions` WHERE `submissions`.`id` = 132405 LIMIT 1 

Deadlettered logging

> Deadletter Exception: MySQL client is not connected

And the actual logging of these errors is:
```
warn "Re-queue Exception: #{exception.message}"
```
And
```
error "Deadletter Exception: #{exception.message}"
```

So *very* similar but not identical exception messages. While we don't know the class, the latter exception doesn't match the regexp, so it makes sense that it will be dead-lettered. This is exactly the type of issue that the new approach is intended to resolve. So yay!

**Comment by JamesGlover** [comment]
All issues discussed above should now be resolved.
